// 项目级 build.gradle
buildscript {
    repositories {
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-google/' }
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
